-- V6__Fix_Missing_Audit_Columns.sql

ALTER TABLE message_reactions
    ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT now() NOT NULL;

ALTER TABLE message_reads
    ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT now() NOT NULL;

ALTER TABLE attachments
    ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT now() NOT NULL;

ALTER TABLE notifications
    ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT now() NOT NULL;

ALTER TABLE roles
    ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT now() NOT NULL,
    ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT now() NOT NULL,
    ADD COLUMN IF NOT EXISTS deleted BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMP;

ALTER TABLE permissions
    ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT now() NOT NULL,
    ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT now() NOT NULL,
    ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMP;