package com.teams.teams.domain;

public enum NotificationType {
    MESSAGE_RECEIVED,
    DIRECT_MESSAGE,
    CHANNEL_MESSAGE,
    MESSAGE_REPLY,
    MESSAGE_WITH_ATTACHMENT,
    USER_MENTIONED,
    TEAM_MENTIONED,
    CHANNEL_MENTIONED,
    TEAM_INVITATION,
    CHANNEL_INVITATION,
    MEMBER_ADDED,
    MEMBER_REMOVED,
    TEAM_ADDED,
    TEAM_REMOVED,
    TEAM_ROLE_CHANGED,
    CHANNEL_ADDED,
    CHANNEL_REMOVED,
    CHANNEL_ROLE_CHANGED,
    TEAM_CREATED,
    CHANNEL_CREATED,
    INCOMING_VIDEO_CALL,
    MISSED_VIDEO_CALL,
    GROUP_VIDEO_CALL,
    CALL_CANCELLED,
    CALL_DECLINED,
    CALL_FAILED,
    MESSAGE_MENTION,
    TEAM_UPDATED,
    CHANNEL_UPDATED
}

